name       : horizon-eda
version    : 2.4.0
release    : 7
source     :
    - https://github.com/horizon-eda/horizon/archive/refs/tags/v2.4.0.tar.gz : e1165ec11dc222fd5c41a1da752b2aae44eca80f6f785dd4069dcdd225ae1d53
license    : GPL-3.0-or-later
component  : office.scientific
summary    : Horizon is a free EDA package
description: |
    Horizon EDA is an Electronic Design Automation package supporting an integrated end-to-end workflow for printed circuit board design including parts management and schematic entry.
builddeps  :
    - pkgconfig(glm)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(libcurl)
    - pkgconfig(libgit2)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libpodofo)
    - pkgconfig(libzmq)
    - pkgconfig(sqlite3)
    - cppzmq
    - libboost-devel
    - opencascade-devel
setup      : |
    %patch -p1 < $pkgfiles/use-bfd-linker.patch
build      : |
    %make PREFIX=/usr WITH_SPNAV=0
install    : |
    %make_install PREFIX=/usr
    %make install-man DESTDIR=$installdir PREFIX=/usr
