name       : horizon-eda
version    : 2.3.1
release    : 6
source     :
    - https://github.com/horizon-eda/horizon/archive/refs/tags/v2.3.1.tar.gz : 478632ce6c758884f16ae1f25c1f94358988051697124c4473f8e7d914e7320c
license    : GPL-3.0-or-later
component  : office.scientific
summary    : Horizon is a free EDA package
description: |
    Horizon EDA is an Electronic Design Automation package supporting an integrated end-to-end workflow for printed circuit board design including parts management and schematic entry.
clang      : true
builddeps  :
    - pkgconfig(glm)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(libcurl)
    - pkgconfig(libgit2)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libpodofo)
    - pkgconfig(libzmq)
    - pkgconfig(sqlite3)
    - binutils-gold
    - cppzmq
    - libboost-devel
    - opencascade-devel
build      : |
    %make PREFIX=/usr WITH_SPNAV=0
install    : |
    %make_install PREFIX=/usr
    %make install-man DESTDIR=$installdir PREFIX=/usr
