name       : horizon-eda
version    : 2.1.0
release    : 2
source     :
    - https://github.com/horizon-eda/horizon/archive/refs/tags/v2.1.0.tar.gz : 2ba7a64ef0d8f22ad12e6a5a9c108f865eeb468f954f51ee5fbc03e6a847549a
license    : GPL-3.0-or-later
component  : office.scientific
summary    : Horizon is a free EDA package
homepage   : https://horizon-eda.org/
description: |
    Horizon EDA is an Electronic Design Automation package supporting an integrated end-to-end workflow for printed circuit board design including parts management and schematic entry.
clang      : true
builddeps  :
    - pkgconfig(glm)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libgit2)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libpodofo-0)
    - pkgconfig(libzip)
    - pkgconfig(libzmq)
    - pkgconfig(sqlite3)
    - binutils-gold
    - cppzmq
    - libboost-devel
    - opencascade-ce-devel
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    %make install-man DESTDIR=$installdir PREFIX=/usr
