name       : horizon-eda
version    : 2.2.0
release    : 5
source     :
    - https://github.com/horizon-eda/horizon/archive/refs/tags/v2.2.0.tar.gz : 6c04f2fe8a9e1ee148cd1aaf9d418eec2ebce1bdda1741c7a54fb53c95798f91
homepage   : https://horizon-eda.org/
license    : GPL-3.0-or-later
component  : office.scientific
summary    : Horizon is a free EDA package
description: |
    Horizon EDA is an Electronic Design Automation package supporting an integrated end-to-end workflow for printed circuit board design including parts management and schematic entry.
clang      : true
builddeps  :
    - pkgconfig(glm)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libgit2)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libpodofo)
    - pkgconfig(libzip)
    - pkgconfig(libzmq)
    - pkgconfig(sqlite3)
    - binutils-gold
    - cppzmq
    - libboost-devel
    - opencascade-devel
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
    %make install-man DESTDIR=$installdir PREFIX=/usr
